[package]
name = "ingest"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ingest"
path = "src/main.rs"

[dependencies]
schema    = { workspace = true }
ghost-log = { workspace = true }
tokio     = { workspace = true }
tracing   = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow    = { workspace = true }
dotenvy   = { workspace = true }

# AIS / NMEA decoding
nmea = "0.7"
